# Generated by Django 4.1.2 on 2022-10-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_waifu_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="waifu", name="rank", field=models.IntegerField(default=0),
        ),
    ]
