# Generated by Django 4.1.2 on 2022-10-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_waifu_rank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waifu",
            name="rank",
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
