# Generated by Django 4.1.2 on 2022-10-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_waifu_rank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waifu",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
